/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import estructura.ListaDoble;
import estructura.Matriz;
import estructura.Objeto;
import java.awt.datatransfer.DataFlavor;


/**
 *
 * @author walter
 */
public class CreacionTablero extends javax.swing.JFrame {
    DataFlavor dataFlavor = new DataFlavor(Objeto.class, Objeto.class.getSimpleName());
    //destino
    PanelTablero ptb;
    //origen
    PanelView pv;
    LabelObjeto lblo;
    ListaDoble ld;
    Matriz m;

    /** Creates new form CreacionTablero
     * @param ld */
    public CreacionTablero(ListaDoble ld) {
        initComponents();
        this.setTitle("Crear Mundo");
        this.ld = ld;
        m = new Matriz(this.ld);
        lblo = new LabelObjeto(this.ld);
        lblo.setBounds(0, 0, 50, 50);
        //DragSource ds = new DragSource();
        pv = new PanelView(this.ld);
        pv.setLayout(null);
        pv.add(lblo);
        ptb = new PanelTablero(this.ld,m,lblo);
        this.add(ptb);
        this.lypSig.add(pv);
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGraficar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnDatos = new javax.swing.JButton();
        lypSig = new javax.swing.JLayeredPane();
        lbltPreview = new javax.swing.JLabel();
        btnAddColumna = new javax.swing.JButton();
        btnAddFila = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGraficar.setText("Graficar");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnDatos.setText("Datos");
        btnDatos.setMaximumSize(new java.awt.Dimension(90, 25));
        btnDatos.setMinimumSize(new java.awt.Dimension(90, 25));
        btnDatos.setPreferredSize(new java.awt.Dimension(90, 25));
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });

        lypSig.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbltPreview.setText("Siguiente:");

        javax.swing.GroupLayout lypSigLayout = new javax.swing.GroupLayout(lypSig);
        lypSig.setLayout(lypSigLayout);
        lypSigLayout.setHorizontalGroup(
            lypSigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lypSigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltPreview)
                .addGap(99, 99, 99))
        );
        lypSigLayout.setVerticalGroup(
            lypSigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lypSigLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbltPreview)
                .addGap(43, 43, 43))
        );
        lypSig.setLayer(lbltPreview, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnAddColumna.setText("+Columna");
        btnAddColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddColumnaActionPerformed(evt);
            }
        });

        btnAddFila.setText("+Fila");
        btnAddFila.setMaximumSize(new java.awt.Dimension(105, 25));
        btnAddFila.setMinimumSize(new java.awt.Dimension(105, 25));
        btnAddFila.setPreferredSize(new java.awt.Dimension(105, 25));
        btnAddFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFilaActionPerformed(evt);
            }
        });

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("-");
        jButton2.setMaximumSize(new java.awt.Dimension(44, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(44, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(44, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("-");
        jButton3.setMaximumSize(new java.awt.Dimension(44, 25));
        jButton3.setMinimumSize(new java.awt.Dimension(44, 25));
        jButton3.setPreferredSize(new java.awt.Dimension(44, 25));

        jButton4.setText("+");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGraficar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(456, 456, 456)
                                .addComponent(lypSig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(103, 103, 103))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAddColumna)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lypSig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar)
                            .addComponent(btnGraficar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddColumna)
                .addGap(24, 24, 24)
                .addComponent(btnAddFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 502, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        // TODO add your handling code here:
        ld.grafica();
        m.graficar();
    }//GEN-LAST:event_btnGraficarActionPerformed

    private void btnAddColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddColumnaActionPerformed
        // TODO add your handling code here:
        m.agregarColumna();
        ptb.adjMatriz();
        ptb.repaint();
    }//GEN-LAST:event_btnAddColumnaActionPerformed

    private void btnAddFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFilaActionPerformed
        // TODO add your handling code here:
        m.agregarFila();
        ptb.adjMatriz();
        ptb.repaint();
    }//GEN-LAST:event_btnAddFilaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        Eliminar el = new Eliminar(this,true,m);
        el.setVisible(true);
        ptb.repaint();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
        // TODO add your handling code here:
        ReporteDatos rd = new ReporteDatos(this,true,ld);
        rd.setVisible(true);
    }//GEN-LAST:event_btnDatosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          ptb.moverXder();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ptb.moverXIzq();
    }//GEN-LAST:event_jButton2ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddColumna;
    private javax.swing.JButton btnAddFila;
    private javax.swing.JButton btnDatos;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel lbltPreview;
    private javax.swing.JLayeredPane lypSig;
    // End of variables declaration//GEN-END:variables


}
