/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import estructura.ListaDoble;

/**
 *
 * @author walter
 */
public class ReporteDatos extends javax.swing.JDialog {
    private final ListaDoble ld;

    /**
     * Creates new form ReporteDatos
     * @param parent
     * @param modal
     * @param ld
     */
    public ReporteDatos(java.awt.Frame parent, boolean modal, ListaDoble ld) {
        super(parent,"Reporte", modal);
        initComponents();
        this.ld = ld;
        this.setResizable(false);
        llenarReporte();
    }

    
    private void llenarReporte(){
        
        tbDatos.getModel().setValueAt("Castillo", 0, 0);
        tbDatos.getModel().setValueAt(ld.getCastillo(), 0, 1);
        
        tbDatos.getModel().setValueAt("Ficha", 1, 0);
        tbDatos.getModel().setValueAt(ld.getFichas(), 1, 1);
        
        tbDatos.getModel().setValueAt("Goomba", 2, 0);
        tbDatos.getModel().setValueAt(ld.getGooba(), 2, 1);
        
        tbDatos.getModel().setValueAt("Hongo", 3, 0);
        tbDatos.getModel().setValueAt(ld.getHongo(), 3, 1);
        
        tbDatos.getModel().setValueAt("Koopa", 4, 0);
        tbDatos.getModel().setValueAt(ld.getKoopa(), 4, 1);
        
        tbDatos.getModel().setValueAt("Mario", 5, 0);
        tbDatos.getModel().setValueAt(ld.getHeroe(), 5, 1);
        
        tbDatos.getModel().setValueAt("Pared", 6, 0);
        tbDatos.getModel().setValueAt(ld.getPared(), 6, 1);
        
        tbDatos.getModel().setValueAt("Suelo", 7, 0);
        tbDatos.getModel().setValueAt(ld.getSuelo(), 7, 1);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tipo", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDatos);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jButton1)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDatos;
    // End of variables declaration//GEN-END:variables
}
